### ISSUE TITLE
How to generate result.png

### ISSUE THREAD

**Issue by getupgetup** [liweizju/ESKF_toy#1]
I can run evaluate_ate.py to get statistic error, but I can't watch it intuitively. Is there any way to generate result.png?

**Comment by liweizju** [comment]
> I can run evaluate_ate.py to get statistic error, but I can't watch it intuitively. Is there any way to generate result.png?

Hi, try add the argument like "--plot result.png" when execute the evaluate_ate.py.

**Comment by getupgetup** [comment]
> > I can run evaluate_ate.py to get statistic error, but I can't watch it intuitively. Is there any way to generate result.png?
> 
> Hi, try add the argument like "--plot result.png" when execute the evaluate_ate.py.

Great! I can get the result.png now. However, it seems that only the result for "gentleWave" is right. Trajectories don't perform good in the other two datasets.What's the reason?

**Comment by liweizju** [comment]
> > > I can run evaluate_ate.py to get statistic error, but I can't watch it intuitively. Is there any way to generate result.png?
> > 
> > 
> > Hi, try add the argument like "--plot result.png" when execute the evaluate_ate.py.
> 
> Great! I can get the result.png now. However, it seems that only the result for "gentleWave" is right. Trajectories don't perform good in the other two datasets.What's the reason?

Hmm... Sorry I didn't check it seriously. Maybe the implementation problem or the algorithm problem, not sure about it. I'll return to the problem when I get some time.

**Comment by getupgetup** [comment]
> > > > I can run evaluate_ate.py to get statistic error, but I can't watch it intuitively. Is there any way to generate result.png?
> > > 
> > > 
> > > Hi, try add the argument like "--plot result.png" when execute the evaluate_ate.py.
> > 
> > 
> > Great! I can get the result.png now. However, it seems that only the result for "gentleWave" is right. Trajectories don't perform good in the other two datasets.What's the reason?
> 
> Hmm... Sorry I didn't check it seriously. Maybe the implementation problem or the algorithm problem, not sure about it. I'll return to the problem when I get some time.
> 
> BTW, before the problem is fixed, you may have a try of the original version: https://github.com/je310/ESKF

Thank u.
